services:
  # ------------------------------Main-------------------------------
  kws_tunnel_gateway:
    image: golang:latest
    container_name: kws_tunnel_gateway
    privileged: true
    volumes:
      - ./src/:/app/data
    network_mode: "host"
    ports:
      - "8081:8081"
    working_dir: /app/data/cmd
    command: sh -c "go run ."

  # Use the postgres and redis of the main KWS project
